"""
Comprehensive Global Asset Universe for FinDashIQ Institutional Stock Scanner.
Categorized across Regional Markets, Sectors, Benchmark Index/ETF Baskets, and Thematic Styles.
Includes 300+ liquid institutional equities and benchmark asset allocation ETFs.
"""

SCANNER_GLOBAL_UNIVERSE = [
    # ==============================================================================
    # 1. 🇺🇸 US MEGA & LARGE CAP LEADERS (S&P 500 / NASDAQ 100 / RUSSELL)
    # ==============================================================================
    # Technology, AI Silicon & Deep Tech
    {"ticker": "NVDA", "name": "NVIDIA Corporation", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "SMH", "marketCapClass": "mega", "esgRating": "Leader (91/100)", "ecoBadge": "⚡ AI GPU Accelerator Monopoly"},
    {"ticker": "MSFT", "name": "Microsoft Corporation", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "QQQ", "marketCapClass": "mega", "esgRating": "Elite (96/100)", "ecoBadge": "⚡ Azure AI & Cloud Enterprise"},
    {"ticker": "AAPL", "name": "Apple Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ Edge AI & Silicon Architecture"},
    {"ticker": "GOOGL", "name": "Alphabet Inc. (Class A)", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "QQQ", "marketCapClass": "mega", "esgRating": "Leader (92/100)", "ecoBadge": "⚡ Gemini AI & Cloud Infrastructure"},
    {"ticker": "GOOG", "name": "Alphabet Inc. (Class C)", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "QQQ", "marketCapClass": "mega", "esgRating": "Leader (92/100)", "ecoBadge": "⚡ Search & DeepMind Research"},
    {"ticker": "AMZN", "name": "Amazon.com Inc.", "market": "us", "sector": "Consumer", "themes": ["ai_deeptech", "momentum"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Advanced (86/100)", "ecoBadge": "⚡ AWS Cloud & Autonomous Logistics"},
    {"ticker": "META", "name": "Meta Platforms Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "mega", "esgRating": "Leader (88/100)", "ecoBadge": "⚡ Llama Open AI & Spatial Reality"},
    {"ticker": "TSLA", "name": "Tesla Inc.", "market": "us", "sector": "Consumer", "themes": ["eco_esg", "momentum"], "parentETF": "QQQ", "marketCapClass": "mega", "esgRating": "Leader (90/100)", "ecoBadge": "🌿 EV & Full Self-Driving Robotaxi"},
    {"ticker": "AVGO", "name": "Broadcom Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SMH", "marketCapClass": "mega", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ Custom AI ASICs & Optical Fabric"},
    {"ticker": "AMD", "name": "Advanced Micro Devices", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "⚡ Instinct AI Accelerators & EPYC"},
    {"ticker": "QCOM", "name": "Qualcomm Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "⚡ Snapdragon NPU & On-Device AI"},
    {"ticker": "INTC", "name": "Intel Corporation", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Advanced (85/100)", "ecoBadge": "⚡ Foundry 18A & Gaudi AI"},
    {"ticker": "TXN", "name": "Texas Instruments", "market": "us", "sector": "Technology", "themes": ["value"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Analog Power Management & Auto"},
    {"ticker": "ADI", "name": "Analog Devices", "market": "us", "sector": "Technology", "themes": ["value"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "⚡ Precision Analog & Industrial IoT"},
    {"ticker": "MU", "name": "Micron Technology", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "⚡ High-Bandwidth Memory (HBM3E)"},
    {"ticker": "AMAT", "name": "Applied Materials", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "⚡ Semiconductor Fab Equipment"},
    {"ticker": "LRCX", "name": "Lam Research", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ Etch & Deposition Wafer Tech"},
    {"ticker": "KLAC", "name": "KLA Corporation", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "⚡ Process Control & Yield Metrology"},
    {"ticker": "ARM", "name": "Arm Holdings", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "⚡ Ultra-Low Power RISC Architecture"},
    {"ticker": "SMCI", "name": "Super Micro Computer", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Advanced (85/100)", "ecoBadge": "⚡ AI Direct Liquid Cooled Servers"},
    {"ticker": "ANET", "name": "Arista Networks", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "⚡ 800G AI Ethernet Switching"},
    {"ticker": "MRVL", "name": "Marvell Technology", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Advanced (87/100)", "ecoBadge": "⚡ Custom AI Silicon & Optical DSP"},
    {"ticker": "NXPI", "name": "NXP Semiconductors", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ Automotive Microcontrollers & Radar"},
    {"ticker": "ON", "name": "ON Semiconductor", "market": "us", "sector": "Technology", "themes": ["eco_esg", "value"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "🌿 Silicon Carbide (SiC) Power Modules"},
    {"ticker": "MCHP", "name": "Microchip Technology", "market": "us", "sector": "Technology", "themes": ["value"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Embedded Controllers & Flash Memory"},
    {"ticker": "MPWR", "name": "Monolithic Power Systems", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "⚡ GPU Power Delivery & Server VRMs"},
    {"ticker": "TER", "name": "Teradyne Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "⚡ Automated Chip Testing & Robotics"},
    {"ticker": "ENTG", "name": "Entegris Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "⚡ Advanced Materials & Microcontamination"},
    {"ticker": "CDNS", "name": "Cadence Design Systems", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Elite (94/100)", "ecoBadge": "⚡ Electronic Design Automation (EDA)"},
    {"ticker": "SNPS", "name": "Synopsys Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Elite (95/100)", "ecoBadge": "⚡ Silicon IP & AI Chip Architecture"},
    {"ticker": "DELL", "name": "Dell Technologies", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "⚡ AI Factory PowerEdge Servers"},
    {"ticker": "HPQ", "name": "HP Inc.", "market": "us", "sector": "Technology", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 AI Next-Gen PC & Hybrid Work"},
    {"ticker": "WDC", "name": "Western Digital Corp.", "market": "us", "sector": "Technology", "themes": ["momentum", "ai_deeptech"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "⚡ High-Capacity Enterprise Flash Storage"},
    {"ticker": "STX", "name": "Seagate Technology", "market": "us", "sector": "Technology", "themes": ["momentum", "value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "⚡ HAMR Mass-Capacity Cloud Storage"},
    {"ticker": "ALAB", "name": "Astera Labs Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "SMH", "marketCapClass": "mid", "esgRating": "Advanced (86/100)", "ecoBadge": "⚡ PCIe & CXL AI Connectivity Modules"},
    {"ticker": "ASTS", "name": "AST SpaceMobile", "market": "us", "sector": "Technology", "themes": ["momentum"], "parentETF": "IWM", "marketCapClass": "mid", "esgRating": "Standard (80/100)", "ecoBadge": "🚀 Space-Based Cellular Broadband Network"},
    {"ticker": "RKLB", "name": "Rocket Lab USA", "market": "us", "sector": "Industrial", "themes": ["momentum"], "parentETF": "IWM", "marketCapClass": "mid", "esgRating": "Leader (88/100)", "ecoBadge": "🚀 Electron & Neutron Satellite Launch"},
    {"ticker": "IONQ", "name": "IonQ Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "IWM", "marketCapClass": "mid", "esgRating": "Advanced (84/100)", "ecoBadge": "⚡ Trapped-Ion Quantum Computing"},
    {"ticker": "RGTI", "name": "Rigetti Computing", "market": "us", "sector": "Technology", "themes": ["ai_deeptech"], "parentETF": "IWM", "marketCapClass": "small", "esgRating": "Standard (79/100)", "ecoBadge": "⚡ Superconducting Quantum Processors"},
    {"ticker": "SYM", "name": "Symbotic Inc.", "market": "us", "sector": "Industrial", "themes": ["ai_deeptech", "momentum"], "parentETF": "IWM", "marketCapClass": "mid", "esgRating": "Advanced (85/100)", "ecoBadge": "⚡ AI Warehouse Supply Chain Robotics"},

    # Enterprise Software, Cloud & Cybersecurity
    {"ticker": "ORCL", "name": "Oracle Corporation", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (89/100)", "ecoBadge": "⚡ Hyperscale Cloud & OCI Clusters"},
    {"ticker": "CRM", "name": "Salesforce Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Elite (94/100)", "ecoBadge": "⚡ Agentforce Autonomous AI Agents"},
    {"ticker": "NOW", "name": "ServiceNow Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (93/100)", "ecoBadge": "⚡ Enterprise Workflow GenAI"},
    {"ticker": "ADBE", "name": "Adobe Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Elite (95/100)", "ecoBadge": "⚡ Firefly Generative Media Engine"},
    {"ticker": "INTU", "name": "Intuit Inc.", "market": "us", "sector": "Technology", "themes": ["value"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "⚡ TurboTax & QuickBooks AI"},
    {"ticker": "IBM", "name": "International Business Machines", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 WatsonX & Quantum Computing"},
    {"ticker": "CSCO", "name": "Cisco Systems", "market": "us", "sector": "Technology", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Elite (94/100)", "ecoBadge": "👑 Enterprise Networking & Splunk"},
    {"ticker": "PLTR", "name": "Palantir Technologies", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Advanced (85/100)", "ecoBadge": "⚡ AIP Enterprise AI Platform"},
    {"ticker": "SNOW", "name": "Snowflake Inc.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Advanced (86/100)", "ecoBadge": "⚡ Cortex Data Cloud & Warehouse"},
    {"ticker": "CRWD", "name": "CrowdStrike Holdings", "market": "us", "sector": "Cybersecurity", "themes": ["momentum", "ai_deeptech"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "🛡️ Falcon AI Threat Graph"},
    {"ticker": "PANW", "name": "Palo Alto Networks", "market": "us", "sector": "Cybersecurity", "themes": ["momentum", "ai_deeptech"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "🛡️ Precision AI SASE & XSIAM"},
    {"ticker": "FTNT", "name": "Fortinet Inc.", "market": "us", "sector": "Cybersecurity", "themes": ["value"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "🛡️ Secure Networking ASIC Firewalls"},
    {"ticker": "DDOG", "name": "Datadog Inc.", "market": "us", "sector": "Cybersecurity", "themes": ["momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Advanced (87/100)", "ecoBadge": "⚡ Cloud Observability & LLM Tracing"},
    {"ticker": "NET", "name": "Cloudflare Inc.", "market": "us", "sector": "Cybersecurity", "themes": ["momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Advanced (86/100)", "ecoBadge": "⚡ Global Edge CDN & Workers AI"},
    {"ticker": "ZS", "name": "Zscaler Inc.", "market": "us", "sector": "Cybersecurity", "themes": ["momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Advanced (85/100)", "ecoBadge": "🛡️ Zero Trust Exchange Architecture"},
    {"ticker": "MDB", "name": "MongoDB Inc.", "market": "us", "sector": "Technology", "themes": ["momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Advanced (84/100)", "ecoBadge": "⚡ Atlas Vector Search & NoSQL"},
    {"ticker": "APP", "name": "AppLovin Corp.", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Advanced (86/100)", "ecoBadge": "⚡ AXON 2.0 AI Ad Recommendation Engine"},
    {"ticker": "TTD", "name": "The Trade Desk", "market": "us", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ Kokai AI Programmatic Advertising"},
    {"ticker": "SPOT", "name": "Spotify Technology", "market": "us", "sector": "Technology", "themes": ["momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "⚡ Global Audio Streaming Monopolist"},
    {"ticker": "UBER", "name": "Uber Technologies", "market": "us", "sector": "Technology", "themes": ["momentum"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "⚡ Mobility & Delivery Network Moat"},
    {"ticker": "DASH", "name": "DoorDash Inc.", "market": "us", "sector": "Technology", "themes": ["momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Advanced (85/100)", "ecoBadge": "⚡ Local Logistics & Omnichannel Commerce"},
    {"ticker": "ABNB", "name": "Airbnb Inc.", "market": "us", "sector": "Consumer", "themes": ["value"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Alternative Accommodations Leader"},
    {"ticker": "BKNG", "name": "Booking Holdings", "market": "us", "sector": "Consumer", "themes": ["value", "momentum"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Elite (94/100)", "ecoBadge": "👑 Connected Travel & High Operating Margins"},

    # US Fintech & Financial Infrastructure
    {"ticker": "COIN", "name": "Coinbase Global", "market": "us", "sector": "Fintech", "themes": ["momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Advanced (84/100)", "ecoBadge": "⚡ Institutional Crypto & Base Layer 2"},
    {"ticker": "HOOD", "name": "Robinhood Markets", "market": "us", "sector": "Fintech", "themes": ["momentum"], "parentETF": "IWM", "marketCapClass": "mid", "esgRating": "Advanced (82/100)", "ecoBadge": "⚡ Retail Trading & Gold Yield"},
    {"ticker": "PYPL", "name": "PayPal Holdings", "market": "us", "sector": "Fintech", "themes": ["value"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "💳 Digital Checkout & Venmo Flow"},
    {"ticker": "SOFI", "name": "SoFi Technologies", "market": "us", "sector": "Fintech", "themes": ["momentum"], "parentETF": "IWM", "marketCapClass": "mid", "esgRating": "Advanced (83/100)", "ecoBadge": "💳 Digital Lending & Galileo Banking Core"},
    {"ticker": "AFRM", "name": "Affirm Holdings", "market": "us", "sector": "Fintech", "themes": ["momentum"], "parentETF": "IWM", "marketCapClass": "mid", "esgRating": "Advanced (81/100)", "ecoBadge": "💳 Buy-Now-Pay-Later AI Underwriting"},
    {"ticker": "V", "name": "Visa Inc.", "market": "us", "sector": "Fintech", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Elite (95/100)", "ecoBadge": "👑 Global Payments Duopoly"},
    {"ticker": "MA", "name": "Mastercard Inc.", "market": "us", "sector": "Fintech", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Elite (94/100)", "ecoBadge": "👑 Global Card Rail Network"},
    {"ticker": "AXP", "name": "American Express Co.", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "XLF", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "👑 Premium Closed-Loop Spend Network"},
    {"ticker": "JPM", "name": "JPMorgan Chase & Co.", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "XLF", "marketCapClass": "mega", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Largest US Tier-1 Bank & Trading"},
    {"ticker": "BAC", "name": "Bank of America", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "XLF", "marketCapClass": "mega", "esgRating": "Leader (91/100)", "ecoBadge": "👑 Consumer Banking & Wealth Management"},
    {"ticker": "WFC", "name": "Wells Fargo & Co.", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "XLF", "marketCapClass": "large", "esgRating": "Advanced (84/100)", "ecoBadge": "👑 Commercial Banking & Mortgages"},
    {"ticker": "GS", "name": "Goldman Sachs Group", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "XLF", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 M&A Advisory & Institutional Markets"},
    {"ticker": "MS", "name": "Morgan Stanley", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "XLF", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Wealth Management & Prime Brokerage"},
    {"ticker": "BLK", "name": "BlackRock Inc.", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "XLF", "marketCapClass": "large", "esgRating": "Elite (95/100)", "ecoBadge": "👑 World Largest Asset Manager & iShares"},
    {"ticker": "SCHW", "name": "Charles Schwab Corp.", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "XLF", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Retail Brokerage & RIA Custody Scale"},
    {"ticker": "C", "name": "Citigroup Inc.", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "XLF", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "👑 Cross-Border Institutional Treasury"},
    {"ticker": "SPGI", "name": "S&P Global Inc.", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Elite (95/100)", "ecoBadge": "👑 Credit Ratings & Market Intelligence Moat"},
    {"ticker": "MCO", "name": "Moody's Corporation", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Elite (94/100)", "ecoBadge": "👑 Global Debt Ratings Duopoly"},
    {"ticker": "CME", "name": "CME Group Inc.", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "XLF", "marketCapClass": "large", "esgRating": "Elite (93/100)", "ecoBadge": "👑 Global Derivatives & Futures Exchange"},
    {"ticker": "ICE", "name": "Intercontinental Exchange", "market": "us", "sector": "Financials", "themes": ["value"], "parentETF": "XLF", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "👑 NYSE & Mortgage Technology Rail"},
    {"ticker": "KKR", "name": "KKR & Co. Inc.", "market": "us", "sector": "Financials", "themes": ["momentum", "value"], "parentETF": "XLF", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Private Equity & Infrastructure Alpha"},
    {"ticker": "BX", "name": "Blackstone Inc.", "market": "us", "sector": "Financials", "themes": ["momentum", "value"], "parentETF": "XLF", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 $1T+ Alternative Asset Management"},

    # US Healthcare, BioTech & Medical Devices
    {"ticker": "UNH", "name": "UnitedHealth Group", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "mega", "esgRating": "Leader (91/100)", "ecoBadge": "👑 Optum Care & Managed Healthcare"},
    {"ticker": "LLY", "name": "Eli Lilly and Co.", "market": "us", "sector": "Healthcare", "themes": ["momentum"], "parentETF": "XLV", "marketCapClass": "mega", "esgRating": "Leader (92/100)", "ecoBadge": "⚡ GLP-1 Mounjaro & Neuro Therapeutics"},
    {"ticker": "JNJ", "name": "Johnson & Johnson", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "mega", "esgRating": "Elite (94/100)", "ecoBadge": "👑 MedTech & Innovative Medicine"},
    {"ticker": "ABBV", "name": "AbbVie Inc.", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Skyrizi, Rinvoq & Oncology Pipeline"},
    {"ticker": "MRK", "name": "Merck & Co.", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 Keytruda Immuno-Oncology Monopoly"},
    {"ticker": "PFE", "name": "Pfizer Inc.", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Deep Value BioPharma & Seagen Cancer"},
    {"ticker": "TMO", "name": "Thermo Fisher Scientific", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "👑 Life Sciences Instruments & BioProduction"},
    {"ticker": "ABT", "name": "Abbott Laboratories", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Elite (93/100)", "ecoBadge": "👑 Continuous Glucose Monitors & Diagnostics"},
    {"ticker": "ISRG", "name": "Intuitive Surgical", "market": "us", "sector": "Healthcare", "themes": ["momentum"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "⚡ da Vinci Robotic Surgery Ecosystem"},
    {"ticker": "VRTX", "name": "Vertex Pharmaceuticals", "market": "us", "sector": "Healthcare", "themes": ["momentum"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ CRISPR Casgevy & Cystic Fibrosis"},
    {"ticker": "AMGN", "name": "Amgen Inc.", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 Biologics & Horizon Rare Disease"},
    {"ticker": "BMY", "name": "Bristol-Myers Squibb", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Immuno-Oncology & Cardiovascular"},
    {"ticker": "GILD", "name": "Gilead Sciences", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 HIV Lenacapavir & Kite CAR-T"},
    {"ticker": "REGN", "name": "Regeneron Pharmaceuticals", "market": "us", "sector": "Healthcare", "themes": ["value", "momentum"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Elite (93/100)", "ecoBadge": "⚡ Eylea HD & Dupixent Antibodies"},
    {"ticker": "DHR", "name": "Danaher Corporation", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "👑 Bioprocessing & Genomic Analysis"},
    {"ticker": "SYK", "name": "Stryker Corporation", "market": "us", "sector": "Healthcare", "themes": ["momentum"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "⚡ Mako Robotic Orthopedic Surgery"},
    {"ticker": "BSX", "name": "Boston Scientific", "market": "us", "sector": "Healthcare", "themes": ["momentum"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ Farapulse Pulsed Field Ablation"},
    {"ticker": "MDT", "name": "Medtronic plc", "market": "us", "sector": "Healthcare", "themes": ["value"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Cardiovascular & Neuromodulation"},
    {"ticker": "DXCM", "name": "DexCom Inc.", "market": "us", "sector": "Healthcare", "themes": ["momentum"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "⚡ G7 Continuous Glucose Sensor Leader"},
    {"ticker": "ALNY", "name": "Alnylam Pharmaceuticals", "market": "us", "sector": "Healthcare", "themes": ["momentum"], "parentETF": "XLV", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ RNAi Gene Silencing Therapeutics"},

    # US Energy, Materials & Industrials
    {"ticker": "XOM", "name": "Exxon Mobil Corp.", "market": "us", "sector": "Energy", "themes": ["value"], "parentETF": "XLE", "marketCapClass": "mega", "esgRating": "Advanced (82/100)", "ecoBadge": "👑 Permian Basin & Global LNG Infrastructure"},
    {"ticker": "CVX", "name": "Chevron Corporation", "market": "us", "sector": "Energy", "themes": ["value"], "parentETF": "XLE", "marketCapClass": "mega", "esgRating": "Advanced (83/100)", "ecoBadge": "👑 Integrated Deepwater & Hess Guyana"},
    {"ticker": "COP", "name": "ConocoPhillips", "market": "us", "sector": "Energy", "themes": ["value"], "parentETF": "XLE", "marketCapClass": "large", "esgRating": "Advanced (84/100)", "ecoBadge": "👑 Low Cost E&P & Marathon Asset Synergy"},
    {"ticker": "SLB", "name": "SLB (Schlumberger)", "market": "us", "sector": "Energy", "themes": ["value"], "parentETF": "XLE", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Digital Oilfield Subsurface Tech"},
    {"ticker": "EOG", "name": "EOG Resources", "market": "us", "sector": "Energy", "themes": ["value"], "parentETF": "XLE", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "👑 Premium Drilling ROI & Natural Gas"},
    {"ticker": "OXY", "name": "Occidental Petroleum", "market": "us", "sector": "Energy", "themes": ["value"], "parentETF": "XLE", "marketCapClass": "large", "esgRating": "Advanced (83/100)", "ecoBadge": "👑 Direct Air Capture & Berkshire Backed"},
    {"ticker": "LNG", "name": "Cheniere Energy", "market": "us", "sector": "Energy", "themes": ["momentum", "value"], "parentETF": "XLE", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "⚡ US LNG Export Infrastructure Monopoly"},
    {"ticker": "LIN", "name": "Linde plc", "market": "us", "sector": "Industrial", "themes": ["eco_esg", "value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Elite (96/100)", "ecoBadge": "🌿 Industrial Gases & Green Clean Hydrogen"},
    {"ticker": "APD", "name": "Air Products and Chemicals", "market": "us", "sector": "Industrial", "themes": ["eco_esg", "value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "🌿 Megawatt Hydrogen Production Plants"},
    {"ticker": "FCX", "name": "Freeport-McMoRan", "market": "us", "sector": "Industrial", "themes": ["momentum", "eco_esg"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "🌿 Electrification Copper Mining Giant"},
    {"ticker": "NEM", "name": "Newmont Corporation", "market": "us", "sector": "Industrial", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 World Largest Gold Producer"},
    {"ticker": "NUE", "name": "Nucor Corporation", "market": "us", "sector": "Industrial", "themes": ["value", "eco_esg"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Elite (93/100)", "ecoBadge": "🌿 Low-Emissions Electric Arc Furnace Steel"},
    {"ticker": "ALB", "name": "Albemarle Corporation", "market": "us", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "🌿 Global EV Battery Grade Lithium"},
    {"ticker": "CAT", "name": "Caterpillar Inc.", "market": "us", "sector": "Industrial", "themes": ["value", "momentum"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Heavy Mining & Construction Machinery"},
    {"ticker": "DE", "name": "Deere & Co.", "market": "us", "sector": "Industrial", "themes": ["value"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 Autonomous Precision Agriculture"},
    {"ticker": "GE", "name": "GE Aerospace", "market": "us", "sector": "Industrial", "themes": ["momentum"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ Commercial Jet Engines & LEAP Turbines"},
    {"ticker": "HON", "name": "Honeywell International", "market": "us", "sector": "Industrial", "themes": ["value"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Building Automation & Quantinuum"},
    {"ticker": "UNP", "name": "Union Pacific Corp.", "market": "us", "sector": "Industrial", "themes": ["value"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Western US Transcontinental Freight Rail"},
    {"ticker": "RTX", "name": "RTX Corporation", "market": "us", "sector": "Industrial", "themes": ["value"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "👑 Pratt & Whitney Defense Missiles"},
    {"ticker": "LMT", "name": "Lockheed Martin Corp.", "market": "us", "sector": "Industrial", "themes": ["value"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "👑 F-35 Stealth Fighter Aerospace"},
    {"ticker": "BA", "name": "The Boeing Company", "market": "us", "sector": "Industrial", "themes": ["value"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Standard (80/100)", "ecoBadge": "👑 Commercial Aviation Duopoly Backlog"},
    {"ticker": "NOC", "name": "Northrop Grumman", "market": "us", "sector": "Industrial", "themes": ["value"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 B-21 Raider Stealth Bomber & Defense"},
    {"ticker": "GD", "name": "General Dynamics", "market": "us", "sector": "Industrial", "themes": ["value"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Gulfstream Jets & Nuclear Submarines"},
    {"ticker": "ETN", "name": "Eaton Corporation plc", "market": "us", "sector": "Industrial", "themes": ["ai_deeptech", "momentum", "eco_esg"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Elite (95/100)", "ecoBadge": "⚡ AI Data Center Power & Grid Megaprojects"},
    {"ticker": "EMR", "name": "Emerson Electric Co.", "market": "us", "sector": "Industrial", "themes": ["value"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 Industrial Process Automation Software"},
    {"ticker": "PH", "name": "Parker-Hannifin Corp.", "market": "us", "sector": "Industrial", "themes": ["momentum", "value"], "parentETF": "XLI", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Motion & Control Precision Technologies"},
    {"ticker": "WM", "name": "Waste Management Inc.", "market": "us", "sector": "Industrial", "themes": ["eco_esg", "value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Elite (94/100)", "ecoBadge": "🌿 Landfill Renewable Natural Gas & Recycling"},

    # US Consumer, Retail & Staples
    {"ticker": "WMT", "name": "Walmart Inc.", "market": "us", "sector": "Consumer", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Global Omnichannel Retail Giant"},
    {"ticker": "COST", "name": "Costco Wholesale Corp.", "market": "us", "sector": "Consumer", "themes": ["momentum", "value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (92/100)", "ecoBadge": "👑 Warehouse Club Membership Moat"},
    {"ticker": "PG", "name": "Procter & Gamble Co.", "market": "us", "sector": "Consumer", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Elite (94/100)", "ecoBadge": "👑 Dividend King Consumer Staples"},
    {"ticker": "KO", "name": "Coca-Cola Co.", "market": "us", "sector": "Consumer", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 60+ Year Dividend Aristocrat"},
    {"ticker": "PEP", "name": "PepsiCo Inc.", "market": "us", "sector": "Consumer", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "👑 Frito-Lay Snacks & Beverages"},
    {"ticker": "MCD", "name": "McDonald's Corp.", "market": "us", "sector": "Consumer", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Global Fast Food Franchise Real Estate"},
    {"ticker": "NKE", "name": "NIKE Inc.", "market": "us", "sector": "Consumer", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Athletic Footwear Innovation"},
    {"ticker": "HD", "name": "The Home Depot", "market": "us", "sector": "Consumer", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (92/100)", "ecoBadge": "👑 Home Improvement & Pro Contractor Moat"},
    {"ticker": "LOW", "name": "Lowe's Companies", "market": "us", "sector": "Consumer", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 50+ Year Dividend King Retailer"},
    {"ticker": "TGT", "name": "Target Corporation", "market": "us", "sector": "Consumer", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Omnichannel Merchandising Scale"},
    {"ticker": "TJX", "name": "The TJX Companies", "market": "us", "sector": "Consumer", "themes": ["momentum", "value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 Off-Price Apparel & HomeGoods Moat"},
    {"ticker": "LULU", "name": "Lululemon Athletica", "market": "us", "sector": "Consumer", "themes": ["momentum"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ Technical Athletic Apparel Innovation"},
    {"ticker": "SBUX", "name": "Starbucks Corporation", "market": "us", "sector": "Consumer", "themes": ["value"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Global Coffee Brand & Loyalty Ecosystem"},
    {"ticker": "CMG", "name": "Chipotle Mexican Grill", "market": "us", "sector": "Consumer", "themes": ["momentum"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Elite (93/100)", "ecoBadge": "⚡ Fast Casual Digital Ordering Moat"},
    {"ticker": "GME", "name": "GameStop Corp.", "market": "us", "sector": "Consumer", "themes": ["momentum"], "parentETF": "IWM", "marketCapClass": "mid", "esgRating": "Standard (78/100)", "ecoBadge": "🔥 High-Beta Retail Rally & Squeeze"},

    # ==============================================================================
    # 2. 🇪🇺 EUROPEAN BLUE CHIPS & LEADERS (DAX, CAC, SMI, FTSE, AEX, NORDICS)
    # ==============================================================================
    # Semiconductors & High Tech
    {"ticker": "ASML", "name": "ASML Holding N.V.", "market": "europe", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "EXS1.DE", "marketCapClass": "mega", "esgRating": "Elite (96/100)", "ecoBadge": "⚡ High-NA EUV Lithography Monopoly"},
    {"ticker": "SAP.DE", "name": "SAP SE", "market": "europe", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "EXS1.DE", "marketCapClass": "mega", "esgRating": "Elite (95/100)", "ecoBadge": "⚡ Enterprise Cloud ERP & Joule AI"},
    {"ticker": "IFX.DE", "name": "Infineon Technologies AG", "market": "europe", "sector": "Technology", "themes": ["ai_deeptech", "eco_esg"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Elite (94/100)", "ecoBadge": "🌿 SiC/GaN Power Semiconductors & Automotive"},
    {"ticker": "DTE.DE", "name": "Deutsche Telekom AG", "market": "europe", "sector": "Technology", "themes": ["value"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "👑 T-Mobile US Majority Rail & 5G"},
    {"ticker": "CAP.PA", "name": "Capgemini SE", "market": "europe", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Elite (94/100)", "ecoBadge": "⚡ AI Enterprise Cloud Consulting"},
    {"ticker": "DSY.PA", "name": "Dassault Systèmes SE", "market": "europe", "sector": "Technology", "themes": ["ai_deeptech"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Elite (95/100)", "ecoBadge": "⚡ 3DEXPERIENCE Virtual Twin Platform"},
    {"ticker": "REL.L", "name": "RELX PLC", "market": "europe", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Elite (96/100)", "ecoBadge": "⚡ Legal & Scientific AI Analytics Moat"},

    # Industrial, Aerospace, Defense & Automotive
    {"ticker": "SIE.DE", "name": "Siemens AG", "market": "europe", "sector": "Industrial", "themes": ["eco_esg", "value"], "parentETF": "EXS1.DE", "marketCapClass": "mega", "esgRating": "Elite (95/100)", "ecoBadge": "🌿 Smart Grid & Industrial Digital Twin"},
    {"ticker": "RHM.DE", "name": "Rheinmetall AG", "market": "europe", "sector": "Industrial", "themes": ["momentum"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "🛡️ European Defense Munitions & Leopard Systems"},
    {"ticker": "AIR.PA", "name": "Airbus SE", "market": "europe", "sector": "Industrial", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 A321neo Commercial Duopoly Backlog"},
    {"ticker": "SU.PA", "name": "Schneider Electric S.E.", "market": "europe", "sector": "Industrial", "themes": ["eco_esg", "momentum"], "parentETF": "VGK", "marketCapClass": "mega", "esgRating": "Elite (97/100)", "ecoBadge": "🌿 AI Data Center Power Management"},
    {"ticker": "SAF.PA", "name": "Safran S.A.", "market": "europe", "sector": "Industrial", "themes": ["momentum"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ LEAP Aircraft Engines & Defense Avionics"},
    {"ticker": "HO.PA", "name": "Thales Group", "market": "europe", "sector": "Cybersecurity", "themes": ["momentum"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "🛡️ Aerospace Radar, Space & Cybersecurity"},
    {"ticker": "DHL.DE", "name": "DHL Group (Deutsche Post)", "market": "europe", "sector": "Industrial", "themes": ["value"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 Global Air & Ocean Express Freight"},
    {"ticker": "BMW.DE", "name": "Bayerische Motoren Werke AG", "market": "europe", "sector": "Consumer", "themes": ["value", "eco_esg"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "🌿 Neue Klasse Premium Electric Drive"},
    {"ticker": "MBG.DE", "name": "Mercedes-Benz Group AG", "market": "europe", "sector": "Consumer", "themes": ["value"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Luxury Automotive & Top Dividend Yield"},
    {"ticker": "VOW3.DE", "name": "Volkswagen AG", "market": "europe", "sector": "Consumer", "themes": ["value"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Advanced (85/100)", "ecoBadge": "👑 Global Auto Scale & PowerCo Batteries"},
    {"ticker": "BAS.DE", "name": "BASF SE", "market": "europe", "sector": "Industrial", "themes": ["value", "eco_esg"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "🌿 Green Chemical Transition & Battery Materials"},
    {"ticker": "ENR.DE", "name": "Siemens Energy AG", "market": "europe", "sector": "Clean Energy", "themes": ["eco_esg", "momentum"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "🌿 Grid Electrification & Gas Turbines"},

    # European Financials, Insurance & Asset Management
    {"ticker": "ALV.DE", "name": "Allianz SE", "market": "europe", "sector": "Financials", "themes": ["value"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Elite (94/100)", "ecoBadge": "👑 High-Yield European Insurance & PIMCO"},
    {"ticker": "DB1.DE", "name": "Deutsche Börse AG", "market": "europe", "sector": "Financials", "themes": ["value"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Elite (93/100)", "ecoBadge": "👑 Eurex Derivatives & SimCorp Pre-Trade"},
    {"ticker": "BNP.PA", "name": "BNP Paribas S.A.", "market": "europe", "sector": "Financials", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 Largest Eurozone Banking Group"},
    {"ticker": "SAN.MC", "name": "Banco Santander S.A.", "market": "europe", "sector": "Financials", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Retail Banking in Spain, UK & Latin America"},
    {"ticker": "HSBA.L", "name": "HSBC Holdings plc", "market": "europe", "sector": "Financials", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "mega", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Global Banking with Massive Asian Wealth Core"},
    {"ticker": "UBSG.SW", "name": "UBS Group AG", "market": "europe", "sector": "Financials", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 $5T+ Global Wealth Management Powerhouse"},
    {"ticker": "ZURN.SW", "name": "Zurich Insurance Group", "market": "europe", "sector": "Financials", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Elite (95/100)", "ecoBadge": "👑 Global Commercial & Property Casualty Moat"},

    # European Luxury, Consumer & Pharmaceuticals
    {"ticker": "MC.PA", "name": "LVMH Moët Hennessy Louis Vuitton", "market": "europe", "sector": "Consumer", "themes": ["value", "momentum"], "parentETF": "VGK", "marketCapClass": "mega", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Global Luxury Heritage Icon"},
    {"ticker": "OR.PA", "name": "L'Oréal S.A.", "market": "europe", "sector": "Consumer", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Elite (95/100)", "ecoBadge": "👑 High-Margin Global Beauty & Derma"},
    {"ticker": "RMS.PA", "name": "Hermès International", "market": "europe", "sector": "Consumer", "themes": ["momentum", "value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "👑 Ultra-Exclusive Birkin Luxury Pricing Power"},
    {"ticker": "KER.PA", "name": "Kering S.A. (Gucci)", "market": "europe", "sector": "Consumer", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Luxury Fashion & Saint Laurent"},
    {"ticker": "NESN.SW", "name": "Nestlé S.A.", "market": "europe", "sector": "Consumer", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "mega", "esgRating": "Elite (93/100)", "ecoBadge": "👑 Global Nutrition & Petcare Pricing Moat"},
    {"ticker": "UL", "name": "Unilever PLC", "market": "europe", "sector": "Consumer", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Elite (94/100)", "ecoBadge": "👑 Emerging Market Personal Care Distribution"},
    {"ticker": "NOVO-B.CO", "name": "Novo Nordisk A/S", "market": "europe", "sector": "Healthcare", "themes": ["momentum"], "parentETF": "VGK", "marketCapClass": "mega", "esgRating": "Elite (96/100)", "ecoBadge": "⚡ Ozempic & Wegovy Obesity Market Champion"},
    {"ticker": "NOVN.SW", "name": "Novartis AG", "market": "europe", "sector": "Healthcare", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "mega", "esgRating": "Elite (95/100)", "ecoBadge": "👑 Radioligand Therapy & Entresto Cardio"},
    {"ticker": "SAN.PA", "name": "Sanofi S.A.", "market": "europe", "sector": "Healthcare", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 Dupixent Immunology Blockbuster"},
    {"ticker": "AZN", "name": "AstraZeneca plc", "market": "europe", "sector": "Healthcare", "themes": ["momentum"], "parentETF": "VGK", "marketCapClass": "mega", "esgRating": "Elite (94/100)", "ecoBadge": "⚡ Enhertu ADC Oncology Blockbuster"},
    {"ticker": "GSK.L", "name": "GSK plc", "market": "europe", "sector": "Healthcare", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Arexvy RSV Vaccine & Shingrix"},
    {"ticker": "BAYN.DE", "name": "Bayer AG", "market": "europe", "sector": "Healthcare", "themes": ["value"], "parentETF": "EXS1.DE", "marketCapClass": "mid", "esgRating": "Advanced (83/100)", "ecoBadge": "👑 Crop Science & Cardiovascular Pharma"},
    {"ticker": "MRK.DE", "name": "Merck KGaA", "market": "europe", "sector": "Healthcare", "themes": ["value"], "parentETF": "EXS1.DE", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "⚡ Semiconductor Liquid Crystals & Oncology"},
    {"ticker": "SHEL", "name": "Shell plc", "market": "europe", "sector": "Energy", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "mega", "esgRating": "Leader (88/100)", "ecoBadge": "👑 Global LNG Fleet & Deepwater Oil"},
    {"ticker": "TTE.PA", "name": "TotalEnergies SE", "market": "europe", "sector": "Energy", "themes": ["value", "eco_esg"], "parentETF": "VGK", "marketCapClass": "mega", "esgRating": "Leader (90/100)", "ecoBadge": "🌿 Integrated LNG & Multi-GW Solar Pipeline"},
    {"ticker": "BP.L", "name": "BP p.l.c.", "market": "europe", "sector": "Energy", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "large", "esgRating": "Advanced (84/100)", "ecoBadge": "👑 Deepwater Gulf of Mexico & Gas Flow"},

    # Clean Energy & European Decarbonization
    {"ticker": "VWS.CO", "name": "Vestas Wind Systems", "market": "europe", "sector": "Clean Energy", "themes": ["eco_esg"], "parentETF": "ICLN", "marketCapClass": "large", "esgRating": "Elite (95/100)", "ecoBadge": "🌿 Offshore V236-15MW Wind Turbine Tech"},
    {"ticker": "ORSTED.CO", "name": "Ørsted A/S", "market": "europe", "sector": "Clean Energy", "themes": ["eco_esg"], "parentETF": "ICLN", "marketCapClass": "large", "esgRating": "Elite (97/100)", "ecoBadge": "🌿 Pure-Play Offshore Decarbonization"},
    {"ticker": "NEL.OL", "name": "Nel ASA", "market": "europe", "sector": "Clean Energy", "themes": ["eco_esg", "momentum"], "parentETF": "ICLN", "marketCapClass": "small", "esgRating": "Leader (89/100)", "ecoBadge": "🌿 PEM & Alkaline Green Hydrogen Electrolyzers"},
    {"ticker": "NIBE-B.ST", "name": "NIBE Industrier", "market": "europe", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "🌿 High-Efficiency Building Heat Pumps"},

    # ==============================================================================
    # 3. 🌏 ASIA-PACIFIC DEVELOPED MARKETS (JAPAN, TAIWAN, AUSTRALIA)
    # ==============================================================================
    # Taiwan & Japan Semiconductor Champions
    {"ticker": "TSM", "name": "Taiwan Semiconductor Manufacturing", "market": "asia", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "SMH", "marketCapClass": "mega", "esgRating": "Elite (94/100)", "ecoBadge": "⚡ 2nm/3nm Pure-Play Silicon Foundry"},
    {"ticker": "8035.T", "name": "Tokyo Electron Ltd", "market": "asia", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "SMH", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "⚡ Coater/Developer Wafer Fab Equipment"},
    {"ticker": "6861.T", "name": "Keyence Corporation", "market": "asia", "sector": "Industrial", "themes": ["momentum", "value"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "⚡ Factory Automation Machine Vision"},
    {"ticker": "6954.T", "name": "Fanuc Corporation", "market": "asia", "sector": "Industrial", "themes": ["value"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ Industrial CNC Robotics & Yellow Robomachines"},
    {"ticker": "6758.T", "name": "Sony Group Corp (Tokyo)", "market": "asia", "sector": "Technology", "themes": ["value"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ PlayStation & Premium Audio/Sensors"},
    {"ticker": "SONY", "name": "Sony Group Corporation (ADR)", "market": "asia", "sector": "Technology", "themes": ["value"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ CMOS Image Sensors & Gaming"},
    {"ticker": "9984.T", "name": "SoftBank Group Corp", "market": "asia", "sector": "Technology", "themes": ["ai_deeptech", "momentum"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Advanced (82/100)", "ecoBadge": "⚡ Arm Stake & Vision Fund AI Bets"},
    {"ticker": "7974.T", "name": "Nintendo Co. Ltd.", "market": "asia", "sector": "Consumer", "themes": ["value"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Elite (93/100)", "ecoBadge": "👑 Mario, Zelda & Switch Gaming IP Franchise"},
    {"ticker": "7203.T", "name": "Toyota Motor Corp", "market": "asia", "sector": "Consumer", "themes": ["value"], "parentETF": "EWJ", "marketCapClass": "mega", "esgRating": "Leader (89/100)", "ecoBadge": "👑 World #1 Auto Volume & Solid-State EV"},
    {"ticker": "7267.T", "name": "Honda Motor Co.", "market": "asia", "sector": "Consumer", "themes": ["value"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "👑 Global Motorcycles & Hybrid Autos"},
    {"ticker": "8058.T", "name": "Mitsubishi Corporation", "market": "asia", "sector": "Industrial", "themes": ["value"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "👑 Sogo Shosha Energy & Resource Trading"},
    {"ticker": "8001.T", "name": "Itochu Corporation", "market": "asia", "sector": "Industrial", "themes": ["value"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Leader (92/100)", "ecoBadge": "👑 Berkshire-Backed Japanese Trading Giant"},
    {"ticker": "8306.T", "name": "Mitsubishi UFJ Financial", "market": "asia", "sector": "Financials", "themes": ["value"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Japan Largest Mega-Bank Group"},
    {"ticker": "4568.T", "name": "Daiichi Sankyo", "market": "asia", "sector": "Healthcare", "themes": ["momentum"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Elite (94/100)", "ecoBadge": "⚡ Enhertu ADC Oncology Technology"},

    # Australia & Pacific Champions
    {"ticker": "BHP", "name": "BHP Group Limited", "market": "asia", "sector": "Industrial", "themes": ["value"], "parentETF": "EWA", "marketCapClass": "mega", "esgRating": "Leader (91/100)", "ecoBadge": "👑 World Premier Low-Cost Copper & Iron Ore"},
    {"ticker": "RIO", "name": "Rio Tinto Group", "market": "asia", "sector": "Industrial", "themes": ["value"], "parentETF": "EWA", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Pilbara Iron Ore & Aluminium Decarbonization"},

    # ==============================================================================
    # 4. ⚡ EMERGING MARKETS (INDIA, LATIN AMERICA, GREATER CHINA, SE ASIA)
    # ==============================================================================
    # India Alpha Champions
    {"ticker": "INFY", "name": "Infosys Limited", "market": "emerging", "sector": "Technology", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Elite (93/100)", "ecoBadge": "👑 Global IT Digital Transformation"},
    {"ticker": "HDB", "name": "HDFC Bank Limited", "market": "emerging", "sector": "Financials", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 India Largest Private Retail Bank"},
    {"ticker": "IBN", "name": "ICICI Bank Limited", "market": "emerging", "sector": "Financials", "themes": ["momentum", "value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "⚡ High-ROE Indian Private Banking Leader"},
    {"ticker": "WIT", "name": "Wipro Limited", "market": "emerging", "sector": "Technology", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Elite (93/100)", "ecoBadge": "👑 Cloud Integration & AI Automation"},
    {"ticker": "RDY", "name": "Dr. Reddy's Laboratories", "market": "emerging", "sector": "Healthcare", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "mid", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Global Generic Pharmaceuticals"},

    # Latin America Leaders (Brazil, Mexico, Chile, Argentina)
    {"ticker": "MELI", "name": "MercadoLibre Inc.", "market": "emerging", "sector": "Consumer", "themes": ["momentum"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "⚡ Latin America E-Commerce & Mercado Pago"},
    {"ticker": "NU", "name": "Nu Holdings Ltd. (Nubank)", "market": "emerging", "sector": "Fintech", "themes": ["momentum"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Advanced (86/100)", "ecoBadge": "💳 Digital Banking Leader in Brazil & Mexico"},
    {"ticker": "VALE", "name": "Vale S.A.", "market": "emerging", "sector": "Industrial", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Advanced (84/100)", "ecoBadge": "👑 High-Grade Carajás Iron Ore & Nickel"},
    {"ticker": "ITUB", "name": "Itaú Unibanco Holding", "market": "emerging", "sector": "Financials", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "👑 Latin America Largest Private Bank"},
    {"ticker": "BBD", "name": "Banco Bradesco S.A.", "market": "emerging", "sector": "Financials", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "👑 Brazilian Insurance & Retail Credit"},
    {"ticker": "PBR", "name": "Petróleo Brasileiro (Petrobras)", "market": "emerging", "sector": "Energy", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Advanced (82/100)", "ecoBadge": "👑 Pre-Salt Deepwater Offshore Oil"},
    {"ticker": "ABEV", "name": "Ambev S.A.", "market": "emerging", "sector": "Consumer", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Latin America Brewing Monopoly (AB InBev)"},
    {"ticker": "SQM", "name": "Sociedad Química y Minera de Chile", "market": "emerging", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "🌿 Atacama Brine Lithium & Iodine"},

    # Greater China & SE Asia
    {"ticker": "BABA", "name": "Alibaba Group Holding", "market": "emerging", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Advanced (84/100)", "ecoBadge": "⚡ Qwen Open LLMs & Cloud Intelligence"},
    {"ticker": "JD", "name": "JD.com Inc.", "market": "emerging", "sector": "Consumer", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Advanced (83/100)", "ecoBadge": "👑 Automated Supply Chain & E-Commerce"},
    {"ticker": "PDD", "name": "PDD Holdings Inc.", "market": "emerging", "sector": "Consumer", "themes": ["momentum"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Standard (79/100)", "ecoBadge": "⚡ Temu Global Cross-Border Logistics"},
    {"ticker": "BIDU", "name": "Baidu Inc.", "market": "emerging", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "⚡ ERNIE Bot & Apollo Robotaxi Fleet"},
    {"ticker": "TCEHY", "name": "Tencent Holdings (ADR)", "market": "emerging", "sector": "Technology", "themes": ["ai_deeptech", "value"], "parentETF": "EEM", "marketCapClass": "mega", "esgRating": "Leader (89/100)", "ecoBadge": "⚡ WeChat Super-App & Global Gaming Moat"},
    {"ticker": "NTES", "name": "NetEase Inc.", "market": "emerging", "sector": "Technology", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "👑 Online Gaming & Cloud Music"},
    {"ticker": "TCOM", "name": "Trip.com Group", "market": "emerging", "sector": "Consumer", "themes": ["momentum", "value"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Leader (88/100)", "ecoBadge": "⚡ Asian Outbound Travel Booking Network"},
    {"ticker": "LI", "name": "Li Auto Inc.", "market": "emerging", "sector": "Consumer", "themes": ["eco_esg", "momentum"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Advanced (85/100)", "ecoBadge": "🌿 Extended-Range Premium EV SUVs"},
    {"ticker": "NIO", "name": "NIO Inc.", "market": "emerging", "sector": "Consumer", "themes": ["eco_esg", "momentum"], "parentETF": "EEM", "marketCapClass": "mid", "esgRating": "Advanced (84/100)", "ecoBadge": "🌿 Battery-as-a-Service Swapping Network"},
    {"ticker": "SE", "name": "Sea Limited", "market": "emerging", "sector": "Consumer", "themes": ["momentum"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Advanced (84/100)", "ecoBadge": "⚡ Shopee SE Asia E-Commerce Leader"},
    {"ticker": "GRAB", "name": "Grab Holdings", "market": "emerging", "sector": "Technology", "themes": ["momentum"], "parentETF": "EEM", "marketCapClass": "large", "esgRating": "Advanced (85/100)", "ecoBadge": "⚡ SE Asia Ride-Hailing & Digital Banking"},

    # ==============================================================================
    # 5. 🌿 THEMATIC CLEAN ENERGY, ESG & DECARBONIZATION
    # ==============================================================================
    {"ticker": "ENPH", "name": "Enphase Energy", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "momentum"], "parentETF": "ICLN", "marketCapClass": "mid", "esgRating": "Elite (94/100)", "ecoBadge": "🌿 IQ8 Microinverters & IQ Battery"},
    {"ticker": "FSLR", "name": "First Solar", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "large", "esgRating": "Leader (91/100)", "ecoBadge": "🌿 CadTel Thin-Film Utility PV"},
    {"ticker": "SEDG", "name": "SolarEdge Technologies", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "mid", "esgRating": "Leader (88/100)", "ecoBadge": "🌿 DC Power Optimizers & Smart Inverters"},
    {"ticker": "BEPC", "name": "Brookfield Renewable Corp", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "large", "esgRating": "Elite (96/100)", "ecoBadge": "🌿 34GW Hydro, Wind & Solar Capacity"},
    {"ticker": "RUN", "name": "Sunrun Inc.", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "momentum"], "parentETF": "ICLN", "marketCapClass": "mid", "esgRating": "Advanced (86/100)", "ecoBadge": "🌿 Virtual Power Plants & Solar Subscriptions"},
    {"ticker": "HASI", "name": "HA Sustainable Infrastructure", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "mid", "esgRating": "Leader (92/100)", "ecoBadge": "🌿 Climate Solution Yield & Solar Real Estate"},
    {"ticker": "DQ", "name": "Daqo New Energy", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "mid", "esgRating": "Advanced (84/100)", "ecoBadge": "🌿 N-Type High-Purity Solar Polysilicon"},
    {"ticker": "PLUG", "name": "Plug Power Inc.", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "momentum"], "parentETF": "ICLN", "marketCapClass": "small", "esgRating": "Standard (80/100)", "ecoBadge": "🌿 Liquid Green Hydrogen Plant Network"},
    {"ticker": "BLDP", "name": "Ballard Power Systems", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg"], "parentETF": "ICLN", "marketCapClass": "small", "esgRating": "Leader (88/100)", "ecoBadge": "🌿 Heavy-Duty Fuel Cell Engines for Buses & Marine"},
    {"ticker": "FCEL", "name": "FuelCell Energy Inc.", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg"], "parentETF": "ICLN", "marketCapClass": "small", "esgRating": "Standard (78/100)", "ecoBadge": "🌿 Carbon Capture & Molten Carbonate Fuel Cells"},
    {"ticker": "CHPT", "name": "ChargePoint Holdings", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg"], "parentETF": "ICLN", "marketCapClass": "small", "esgRating": "Advanced (82/100)", "ecoBadge": "🌿 Commercial EV Charging Network in US & Europe"},
    {"ticker": "EVGO", "name": "EVgo Inc.", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg"], "parentETF": "ICLN", "marketCapClass": "small", "esgRating": "Standard (81/100)", "ecoBadge": "🌿 Fast DC Public Charging Infrastructure"},
    {"ticker": "STEM", "name": "Stem Inc.", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "ai_deeptech"], "parentETF": "ICLN", "marketCapClass": "small", "esgRating": "Advanced (83/100)", "ecoBadge": "⚡ Athena AI Smart Battery Storage Software"},
    {"ticker": "NEE", "name": "NextEra Energy Inc.", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "mega", "esgRating": "Elite (96/100)", "ecoBadge": "🌿 World #1 Producer of Wind & Solar Energy"},
    {"ticker": "ARRY", "name": "Array Technologies", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "mid", "esgRating": "Leader (89/100)", "ecoBadge": "🌿 Ground-Mount Single-Axis Solar Trackers"},
    {"ticker": "SHLS", "name": "Shoals Technologies Group", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "mid", "esgRating": "Leader (88/100)", "ecoBadge": "🌿 Electrical Balance of Systems (EBOS) for Solar"},
    {"ticker": "CSIQ", "name": "Canadian Solar Inc.", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "mid", "esgRating": "Leader (88/100)", "ecoBadge": "🌿 Utility-Scale Solar Modules & e-STORAGE Battery"},
    {"ticker": "JKS", "name": "JinkoSolar Holding Co.", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "mid", "esgRating": "Advanced (85/100)", "ecoBadge": "🌿 TOPCon High-Efficiency Photovoltaic Modules"},
    {"ticker": "ORA", "name": "Ormat Technologies", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "mid", "esgRating": "Elite (94/100)", "ecoBadge": "🌿 Baseload Geothermal & Recovered Energy Power"},
    {"ticker": "CWEN", "name": "Clearway Energy Inc.", "market": "clean_energy", "sector": "Clean Energy", "themes": ["eco_esg", "value"], "parentETF": "ICLN", "marketCapClass": "large", "esgRating": "Elite (95/100)", "ecoBadge": "🌿 9GW+ Wind, Solar & Flexible Gas Infrastructure"},

    # ==============================================================================
    # 6. 📊 GLOBAL BENCHMARK & SECTOR ETFS
    # ==============================================================================
    {"ticker": "SPY", "name": "SPDR S&P 500 ETF Trust", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Standard (85/100)", "ecoBadge": "📊 Flagship US Benchmark Index"},
    {"ticker": "QQQ", "name": "Invesco QQQ Trust (NASDAQ 100)", "market": "global_etfs", "sector": "ETF", "themes": ["ai_deeptech", "momentum"], "parentETF": "QQQ", "marketCapClass": "mega", "esgRating": "Leader (89/100)", "ecoBadge": "📊 US Top 100 Non-Financial Tech"},
    {"ticker": "SMH", "name": "VanEck Semiconductor ETF", "market": "global_etfs", "sector": "ETF", "themes": ["ai_deeptech", "momentum"], "parentETF": "SMH", "marketCapClass": "mega", "esgRating": "Leader (91/100)", "ecoBadge": "📊 Global 25 Pure-Play Chipmakers"},
    {"ticker": "ICLN", "name": "iShares Global Clean Energy ETF", "market": "global_etfs", "sector": "ETF", "themes": ["eco_esg"], "parentETF": "ICLN", "marketCapClass": "large", "esgRating": "Elite (96/100)", "ecoBadge": "📊 100 Global Renewable Energy Producers"},
    {"ticker": "EXS1.DE", "name": "iShares Core DAX UCITS ETF", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "EXS1.DE", "marketCapClass": "mega", "esgRating": "Leader (92/100)", "ecoBadge": "📊 German DAX 40 Blue Chips"},
    {"ticker": "EXXT.DE", "name": "iShares NASDAQ 100 ETF (DE)", "market": "global_etfs", "sector": "ETF", "themes": ["ai_deeptech"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "📊 UCITS Tech Benchmark in EUR"},
    {"ticker": "XDWT.DE", "name": "Xtrackers MSCI World IT ETF", "market": "global_etfs", "sector": "ETF", "themes": ["ai_deeptech"], "parentETF": "QQQ", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "📊 Global Developed Tech Giants"},
    {"ticker": "XLK", "name": "Technology Select Sector SPDR", "market": "global_etfs", "sector": "ETF", "themes": ["ai_deeptech"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (91/100)", "ecoBadge": "📊 S&P 500 Information Tech Sector"},
    {"ticker": "XLF", "name": "Financial Select Sector SPDR", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (89/100)", "ecoBadge": "📊 S&P 500 Banking & Insurance"},
    {"ticker": "XLV", "name": "Health Care Select Sector SPDR", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (91/100)", "ecoBadge": "📊 S&P 500 BioPharma & MedTech"},
    {"ticker": "XLE", "name": "Energy Select Sector SPDR", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Advanced (84/100)", "ecoBadge": "📊 S&P 500 Oil, Gas & Consumable Energy"},
    {"ticker": "XLI", "name": "Industrial Select Sector SPDR", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (89/100)", "ecoBadge": "📊 S&P 500 Aerospace & Machinery"},
    {"ticker": "XLP", "name": "Consumer Staples Select Sector SPDR", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (91/100)", "ecoBadge": "📊 S&P 500 Defensive Staples & Food"},
    {"ticker": "XLU", "name": "Utilities Select Sector SPDR", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "📊 S&P 500 Regulated Power & Water"},
    {"ticker": "XLB", "name": "Materials Select Sector SPDR", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "📊 S&P 500 Chemicals & Metals"},
    {"ticker": "XLC", "name": "Communication Services Select Sector", "market": "global_etfs", "sector": "ETF", "themes": ["ai_deeptech"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (90/100)", "ecoBadge": "📊 S&P 500 Interactive Media & Telecom"},
    {"ticker": "XLRE", "name": "Real Estate Select Sector SPDR", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "large", "esgRating": "Leader (89/100)", "ecoBadge": "📊 S&P 500 REITs & Cell Towers"},
    {"ticker": "VGK", "name": "Vanguard FTSE Europe ETF", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "VGK", "marketCapClass": "mega", "esgRating": "Leader (92/100)", "ecoBadge": "📊 1300+ European Equities in 1 Basket"},
    {"ticker": "EEM", "name": "iShares MSCI Emerging Markets ETF", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "mega", "esgRating": "Advanced (85/100)", "ecoBadge": "📊 Asia & Latin America Growth"},
    {"ticker": "VWO", "name": "Vanguard FTSE Emerging Markets ETF", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "EEM", "marketCapClass": "mega", "esgRating": "Advanced (85/100)", "ecoBadge": "📊 5000+ Emerging Equities in 1 Basket"},
    {"ticker": "EWJ", "name": "iShares MSCI Japan ETF", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "EWJ", "marketCapClass": "large", "esgRating": "Leader (90/100)", "ecoBadge": "📊 Japan Top 200 Large/Mid Caps"},
    {"ticker": "IWM", "name": "iShares Russell 2000 ETF", "market": "global_etfs", "sector": "ETF", "themes": ["momentum"], "parentETF": "IWM", "marketCapClass": "mega", "esgRating": "Standard (80/100)", "ecoBadge": "📊 US 2000 Small-Cap Equities"},
    {"ticker": "DIA", "name": "SPDR Dow Jones Industrial Average", "market": "global_etfs", "sector": "ETF", "themes": ["value"], "parentETF": "SPY", "marketCapClass": "mega", "esgRating": "Leader (90/100)", "ecoBadge": "📊 30 US Blue-Chip Megacap Titans"}
]

# Deduplicate by ticker while preserving order
seen_tickers = set()
unique_universe = []
for _item in SCANNER_GLOBAL_UNIVERSE:
    _t = _item['ticker'].strip().upper()
    if _t not in seen_tickers:
        seen_tickers.add(_t)
        unique_universe.append(_item)

SCANNER_GLOBAL_UNIVERSE = unique_universe
SCANNER_UNIVERSE = SCANNER_GLOBAL_UNIVERSE
SCANNER_UNIVERSE_500 = SCANNER_GLOBAL_UNIVERSE
